[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
StateSpaceDynamics = "19cf8126-1d00-4ad8-bf17-4e76d7bc0f6d"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
BenchmarkTools = "1.5.0"
CSV = "0.10.14"
DataFrames = "1.6.1"
Plots = "1.40.5"
PlutoUI = "0.7.59"
TimerOutputs = "0.5.24"
